pipeline {
    agent any

    environment {
        imagename = "hojin19082/serviceb"
        registryCredential = 'docker-hub'
        dockerImage = ''
    }

    stages {         
  
        // gradle build
        stage('Bulid maven') {
          agent any
          steps {
            echo 'Bulid maven'
            dir ('./serviceb'){
                sh """
                ./mvnw clean package 
                """
            }
          }
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }
        
        // docker build
        stage('Bulid Docker') {
          agent any
          steps {
            echo 'Bulid Docker'
            dir ('./serviceb'){
              script {
                  dockerImage = docker.build imagename
              }
            }
          }
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }

        // docker push
        stage('Push Docker') {
          agent any
          steps {
            echo 'Push Docker'
            script {
                docker.withRegistry( '', registryCredential) {
                    dockerImage.push("${currentBuild.number}")  // ex) "1.0"
                }
            }
          }
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }

        stage('Deploy to dev') {
          steps {

              git credentialsId: 'github_cred',
                      url: 'https://github.com/KA-SURFY/argocd.git',
                      branch: 'master'
              
              sh "sed -i 's/msa-serviceb:.*\$/msa-serviceb:${currentBuild.number}/g' msa-work/msa-serviceb-deployment.yaml"
              sh "git config user.name 'hojin19082'"
              sh "git config user.email '905018@naver.com'"
              sh "git add msa-work/msa-serviceb-deployment.yaml"
              sh "git commit -m '[UPDATE] msa-serviceb ${currentBuild.number} image versioning'"

              withCredentials([gitUsernamePassword(credentialsId: 'github_cred', gitToolName: 'git-tool')]) {
                sh "git remote set-url origin https://github.com/KA-SURFY/argocd"
                sh "git push origin master"
              }
            }

           post {
                    failure {
                      echo 'Update 실패ㅠㅠ'
                    }
                    success {
                      echo 'Update 성공!!!!'
                    }
            }
        }
    }
}
